{"tag": "info", "depth": 0, "time": "2019-01-06 20:34:25", "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\10714\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\poco\\proxy.py\", line 26, in wrapped\n    proxy.wait_for_appearance(timeout=proxy.poco._pre_action_wait_for_appearance)\n  File \"C:\\Users\\10714\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\poco\\proxy.py\", line 631, in wait_for_appearance\n    raise PocoTargetTimeout('appearance', self)\npoco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of \"UIObjectProxy of \"text=\u520a\u767b\u79df\u76e4\"\"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"runner.py\", line 49, in runTest\n    exec(self._code[\"code\"], self._code[\"ns\"])\n  File \"c:\\Users\\10714\\Desktop\\reference\\airtest-runner\\cases\\Android\\\u520a\u767b\u79df\u76d8\u6d41\u7a0b.air\\\u520a\u767b\u79df\u76d8\u6d41\u7a0b.py\", line 16, in <module>\n    poco(text=\"\u520a\u767b\u79df\u76e4\").click()\n  File \"C:\\Users\\10714\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\poco\\proxy.py\", line 29, in wrapped\n    raise e\n  File \"C:\\Users\\10714\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\poco\\proxy.py\", line 23, in wrapped\n    return func(proxy, *args, **kwargs)\n  File \"C:\\Users\\10714\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\poco\\proxy.py\", line 283, in click\n    pos_in_percentage = self.get_position(focus)\n  File \"C:\\Users\\10714\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\poco\\proxy.py\", line 563, in get_position\n    pos = self.attr('pos')\n  File \"C:\\Users\\10714\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\poco\\proxy.py\", line 39, in wrapped\n    return func(self, *args, **kwargs)\n  File \"C:\\Users\\10714\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\poco\\proxy.py\", line 684, in attr\n    nodes = self._do_query(multiple=False)\n  File \"C:\\Users\\10714\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\poco\\proxy.py\", line 821, in _do_query\n    raise PocoNoSuchNodeException(self)\npoco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of \"text=\u520a\u767b\u79df\u76e4\"\n"}}
